language:
  - swift
osx_image: xcode11.4
xcode_project: randomUser.xcodeproj 
podfile: ./Podfile
language:
  - swift
osx_image: xcode11.4
script:
  - set -o pipefail && xcodebuild -scheme randomUser -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=13.4' build test
